name: Run Tests

# Trigger the workflow on every push to the repository
on:
  push:
    branches:
      - main  # Replace with your default branch (e.g., main, master, etc.)
  pull_request:
    branches:
      - main  # Replace with your default branch

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the .NET SDK (if your project is .NET-based)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Replace with your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --no-restore
      # Move to project directory
      - name: Move to project directory
        run: cd src/LinkedList
      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal